## Mastering pandas: Load, Clean, Analyze Engineering Student Journey Data

## 🧠 1. Why This Dataset
Real-world data from students

Mix of numerical, categorical, and missing values

Great for demonstrating a full pandas workflow

## 📦 2. Setup & Loading Data

Simple way to read the dataset, if it is available in the same path of the script.

In [1]:

import pandas as pd

df = pd.read_csv('students.csv')

If the file is in another path then we need to pass the entire repository of the input file

In [2]:


df=pd.read_csv("students.csv")
df

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,CTC (LPA),Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,0.00,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99
1,65001423-faeb-4d19-a550-8ea26133a34d,Tina Ballard,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",...,0.00,NaN,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52
2,228aaf1d-8710-4c8d-bfec-001b0df01f34,Meena,19.0,Female,CIVIL,7.08,0.0,84.79,Literary Society,"Data Science, SQL, Machine Learning",...,0.00,NaN,5.79,8.82,7.03,6.92,7.67,6.01,7.75,6.62
3,1aa67474-e200-4157-ad54-c95aaa4d52a8,Christopher Morales,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",...,5.89,Research,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43
4,5122db4a-14c8-44d7-b2f4-e869f69d3dd7,Siddharth,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",...,0.00,NaN,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,27d7e5aa-dc11-40a7-9aff-586f00f8d55b,Anil,19.0,Male,IT,7.69,2.0,92.45,"Cultural Club, Robotics, Entrepreneurship Cell","Java, Web Development, C++, SQL, Data Science",...,0.00,NaN,7.00,7.76,8.93,7.41,7.57,7.15,8.17,7.53
1996,74f43a77-70a1-4e4c-a0c2-460d939618c9,Ramya,23.0,Female,CIVIL,7.25,0.0,96.35,"Entrepreneurship Cell, Literary Society","SQL, Machine Learning, Data Science, Java",...,0.00,NaN,7.36,7.55,6.75,6.36,7.07,5.91,8.10,8.87
1997,88a613b4-a3b8-4f92-a3c9-0c6a86017633,Gregory Fernandez,18.0,Male,EEE,6.92,0.0,75.32,"Literary Society, Sports Club","Web Development, Data Science, SQL",...,0.00,NaN,5.12,5.48,6.98,7.29,7.48,6.70,9.53,6.77
1998,248c7b65-0c61-4277-9e95-44857b54d1a9,Vikram,22.0,Male,CSE,7.09,0.0,94.20,"Entrepreneurship Cell, Cultural Club, Sports Club","Data Science, C++, SQL, Python, Java",...,8.89,Job,8.39,7.11,8.32,5.64,6.56,6.71,6.89,7.08
1999,840d718e-de7b-4218-95bd-11db983c3cbd,Siddharth,20.0,Male,IT,6.52,0.0,60.28,Robotics,"Web Development, Python, Machine Learning, Jav...",...,0.00,NaN,5.96,7.67,6.20,6.05,5.56,6.52,6.92,7.24

To find the shape of our input data

In [3]:

df.shape

(2000, 24)

(2000, 24) here first index is rows and another one is columns

If we need to print our loaded data frame we just call the variable name and it will print first and last 5 rows

In [4]:
df

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,CTC (LPA),Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,0.00,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99
1,65001423-faeb-4d19-a550-8ea26133a34d,Tina Ballard,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",...,0.00,NaN,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52
2,228aaf1d-8710-4c8d-bfec-001b0df01f34,Meena,19.0,Female,CIVIL,7.08,0.0,84.79,Literary Society,"Data Science, SQL, Machine Learning",...,0.00,NaN,5.79,8.82,7.03,6.92,7.67,6.01,7.75,6.62
3,1aa67474-e200-4157-ad54-c95aaa4d52a8,Christopher Morales,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",...,5.89,Research,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43
4,5122db4a-14c8-44d7-b2f4-e869f69d3dd7,Siddharth,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",...,0.00,NaN,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,27d7e5aa-dc11-40a7-9aff-586f00f8d55b,Anil,19.0,Male,IT,7.69,2.0,92.45,"Cultural Club, Robotics, Entrepreneurship Cell","Java, Web Development, C++, SQL, Data Science",...,0.00,NaN,7.00,7.76,8.93,7.41,7.57,7.15,8.17,7.53
1996,74f43a77-70a1-4e4c-a0c2-460d939618c9,Ramya,23.0,Female,CIVIL,7.25,0.0,96.35,"Entrepreneurship Cell, Literary Society","SQL, Machine Learning, Data Science, Java",...,0.00,NaN,7.36,7.55,6.75,6.36,7.07,5.91,8.10,8.87
1997,88a613b4-a3b8-4f92-a3c9-0c6a86017633,Gregory Fernandez,18.0,Male,EEE,6.92,0.0,75.32,"Literary Society, Sports Club","Web Development, Data Science, SQL",...,0.00,NaN,5.12,5.48,6.98,7.29,7.48,6.70,9.53,6.77
1998,248c7b65-0c61-4277-9e95-44857b54d1a9,Vikram,22.0,Male,CSE,7.09,0.0,94.20,"Entrepreneurship Cell, Cultural Club, Sports Club","Data Science, C++, SQL, Python, Java",...,8.89,Job,8.39,7.11,8.32,5.64,6.56,6.71,6.89,7.08
1999,840d718e-de7b-4218-95bd-11db983c3cbd,Siddharth,20.0,Male,IT,6.52,0.0,60.28,Robotics,"Web Development, Python, Machine Learning, Jav...",...,0.00,NaN,5.96,7.67,6.20,6.05,5.56,6.52,6.92,7.24

## 🔍 3. Basic EDA & Exploration
1. df.head(), df.tail()

2. df.info() – check columns and types

3. df.describe() – get a statistical summary

We can also print first 5 rows from our dataset using **head()**

In [5]:

df.head()

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,CTC (LPA),Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,0.00,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99
1,65001423-faeb-4d19-a550-8ea26133a34d,Tina Ballard,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",...,0.00,NaN,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52
2,228aaf1d-8710-4c8d-bfec-001b0df01f34,Meena,19.0,Female,CIVIL,7.08,0.0,84.79,Literary Society,"Data Science, SQL, Machine Learning",...,0.00,NaN,5.79,8.82,7.03,6.92,7.67,6.01,7.75,6.62
3,1aa67474-e200-4157-ad54-c95aaa4d52a8,Christopher Morales,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",...,5.89,Research,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43
4,5122db4a-14c8-44d7-b2f4-e869f69d3dd7,Siddharth,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",...,0.00,NaN,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54

We can also print last 5 rows from our dataset using **tail()**

In [6]:
df.tail()

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,CTC (LPA),Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA
1995,27d7e5aa-dc11-40a7-9aff-586f00f8d55b,Anil,19.0,Male,IT,7.69,2.0,92.45,"Cultural Club, Robotics, Entrepreneurship Cell","Java, Web Development, C++, SQL, Data Science",...,0.00,NaN,7.00,7.76,8.93,7.41,7.57,7.15,8.17,7.53
1996,74f43a77-70a1-4e4c-a0c2-460d939618c9,Ramya,23.0,Female,CIVIL,7.25,0.0,96.35,"Entrepreneurship Cell, Literary Society","SQL, Machine Learning, Data Science, Java",...,0.00,NaN,7.36,7.55,6.75,6.36,7.07,5.91,8.10,8.87
1997,88a613b4-a3b8-4f92-a3c9-0c6a86017633,Gregory Fernandez,18.0,Male,EEE,6.92,0.0,75.32,"Literary Society, Sports Club","Web Development, Data Science, SQL",...,0.00,NaN,5.12,5.48,6.98,7.29,7.48,6.70,9.53,6.77
1998,248c7b65-0c61-4277-9e95-44857b54d1a9,Vikram,22.0,Male,CSE,7.09,0.0,94.20,"Entrepreneurship Cell, Cultural Club, Sports Club","Data Science, C++, SQL, Python, Java",...,8.89,Job,8.39,7.11,8.32,5.64,6.56,6.71,6.89,7.08
1999,840d718e-de7b-4218-95bd-11db983c3cbd,Siddharth,20.0,Male,IT,6.52,0.0,60.28,Robotics,"Web Development, Python, Machine Learning, Jav...",...,0.00,NaN,5.96,7.67,6.20,6.05,5.56,6.52,6.92,7.24

In [7]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain',
       'CTC (LPA)', 'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA',
       'Sem4 GPA', 'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA'],
      dtype='object')

In [8]:
df['Salary']

KeyError: 'Salary'

In [9]:
df['Salary']=df['CTC (LPA)'].apply(lambda x: x*100000 if pd.notna(x) else  x)

In [10]:
df[df['Salary']>1000000]

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
10,e87d1c78-e7c4-41c7-8049-7b717d106c60,Anna Henderson,23.0,Female,EEE,7.17,1.0,73.88,Coding Club,"C++, Python, Machine Learning",...,Research,9.54,7.52,6.41,6.87,8.07,6.42,7.85,4.68,1554000.0
12,1750bd26-bcfc-4af5-9881-a1f0fbbb523a,Pooja,23.0,Female,CIVIL,7.50,1.0,99.10,"Coding Club, Robotics, Sports Club","Java, Python, Web Development, Data Science, C++",...,Job,6.68,7.02,6.66,5.36,8.09,7.90,8.99,9.28,1751000.0
14,f0cd7f05-ea87-455e-a382-95d31e0ef546,Lucas Robinson,20.0,Female,ECE,6.22,1.0,92.43,Sports Club,"Data Science, Machine Learning, Java",...,Startup,7.49,4.15,6.14,5.87,6.74,6.46,7.80,5.14,1912000.0
15,c24369e7-2387-4af6-94c3-a832b231c60b,Joan Smith,23.0,Male,EEE,6.52,0.0,62.63,"Robotics, Entrepreneurship Cell, Cultural Club","Data Science, C++, Python",...,Startup,6.69,6.03,6.17,9.18,6.82,5.64,5.23,6.38,1808000.0
17,7a8d03aa-782a-45e0-88ca-765192f5df7b,Cody Williams,21.0,Female,MECH,7.23,0.0,75.04,"Robotics, Sports Club, Literary Society","Python, Data Science",...,Research,5.99,6.93,7.83,6.97,9.36,7.42,7.23,6.09,1235000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978,2d8ba019-500f-4a92-ad48-f0e37e0710d3,Vikram,22.0,Male,IT,7.92,3.0,62.14,Sports Club,"Java, Python, Machine Learning, Web Developmen...",...,Startup,7.75,7.39,8.18,6.31,8.00,7.16,8.77,9.79,1894000.0
1986,dc9bb95a-8d82-4588-ba3f-476287e09a4b,Amit,19.0,Male,CSE,6.79,1.0,95.93,"Coding Club, Cultural Club","Machine Learning, Web Development",...,Research,6.57,6.46,7.09,7.55,7.12,7.71,5.03,6.78,1710000.0
1989,0b705933-4cde-4b6b-9132-567c51a40d2a,Ashley Sweeney,20.0,Female,MECH,7.46,0.0,76.28,"Coding Club, Literary Society","Java, Machine Learning",...,Higher Studies,8.25,6.20,8.29,6.75,7.76,7.09,9.23,6.11,1452000.0
1990,5e781fd7-94e0-43ba-a9f9-48b24e6384bb,Joseph Coleman,22.0,Male,EEE,7.21,0.0,76.65,"Robotics, Entrepreneurship Cell","Data Science, SQL, Java, Machine Learning",...,Job,6.87,7.99,6.49,5.83,8.21,6.68,7.88,7.76,1118000.0
1994,e0df9d28-94ae-404e-a5ca-3a2257b0e189,Sonal,23.0,Female,MECH,6.79,1.0,93.35,"Sports Club, Coding Club, Literary Society","SQL, Java, Data Science, Web Development",...,Startup,6.87,6.29,7.27,6.09,7.18,7.49,6.78,6.37,1685000.0

In [11]:
df[(df['Salary']>1000000)|(df['Gender']=="Male")]

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99,0.0
1,65001423-faeb-4d19-a550-8ea26133a34d,Tina Ballard,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",...,NaN,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52,0.0
3,1aa67474-e200-4157-ad54-c95aaa4d52a8,Christopher Morales,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",...,Research,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43,589000.0
4,5122db4a-14c8-44d7-b2f4-e869f69d3dd7,Siddharth,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",...,NaN,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54,0.0
5,28dd6ff3-6391-4421-ba38-3c3164b96252,Siddharth,19.0,Male,MECH,7.36,0.0,62.56,Sports Club,"SQL, Python",...,Startup,5.44,9.08,8.13,8.46,7.03,6.64,6.33,7.81,605000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,e0df9d28-94ae-404e-a5ca-3a2257b0e189,Sonal,23.0,Female,MECH,6.79,1.0,93.35,"Sports Club, Coding Club, Literary Society","SQL, Java, Data Science, Web Development",...,Startup,6.87,6.29,7.27,6.09,7.18,7.49,6.78,6.37,1685000.0
1995,27d7e5aa-dc11-40a7-9aff-586f00f8d55b,Anil,19.0,Male,IT,7.69,2.0,92.45,"Cultural Club, Robotics, Entrepreneurship Cell","Java, Web Development, C++, SQL, Data Science",...,NaN,7.00,7.76,8.93,7.41,7.57,7.15,8.17,7.53,0.0
1997,88a613b4-a3b8-4f92-a3c9-0c6a86017633,Gregory Fernandez,18.0,Male,EEE,6.92,0.0,75.32,"Literary Society, Sports Club","Web Development, Data Science, SQL",...,NaN,5.12,5.48,6.98,7.29,7.48,6.70,9.53,6.77,0.0
1998,248c7b65-0c61-4277-9e95-44857b54d1a9,Vikram,22.0,Male,CSE,7.09,0.0,94.20,"Entrepreneurship Cell, Cultural Club, Sports Club","Data Science, C++, SQL, Python, Java",...,Job,8.39,7.11,8.32,5.64,6.56,6.71,6.89,7.08,889000.0
1999,840d718e-de7b-4218-95bd-11db983c3cbd,Siddharth,20.0,Male,IT,6.52,0.0,60.28,Robotics,"Web Development, Python, Machine Learning, Jav...",...,NaN,5.96,7.67,6.20,6.05,5.56,6.52,6.92,7.24,0.0

In [12]:
df[(df['Salary']>1000000)&(df['Gender']=="Male")]

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
15,c24369e7-2387-4af6-94c3-a832b231c60b,Joan Smith,23.0,Male,EEE,6.52,0.0,62.63,"Robotics, Entrepreneurship Cell, Cultural Club","Data Science, C++, Python",...,Startup,6.69,6.03,6.17,9.18,6.82,5.64,5.23,6.38,1808000.0
44,69bcdf4c-f0f4-4cf5-ae95-1c33ed5d4e6b,Vikram,19.0,Male,MECH,6.63,0.0,99.38,"Sports Club, Coding Club","Python, Java, Data Science, C++",...,Research,6.31,7.69,6.68,5.84,7.20,7.40,7.56,4.38,1433000.0
55,dfd410a5-920d-434b-bd1d-6eabacc0b7b9,Rahul,19.0,Male,ECE,7.27,2.0,75.31,Sports Club,"Data Science, Machine Learning, C++, Web Devel...",...,Job,6.60,6.79,7.44,6.21,8.04,7.75,7.02,8.32,1195000.0
69,713b7bd8-ecea-4668-8c31-a7deab2ec2d0,Rakesh,22.0,Male,CIVIL,7.66,1.0,64.73,Coding Club,"Machine Learning, SQL",...,Startup,6.46,8.24,6.41,7.08,7.83,7.45,8.35,9.49,1593000.0
75,c2baf0e0-2179-43f0-a612-4ab4f9b21e6e,Justin Flores,18.0,Male,EEE,6.66,0.0,97.74,"Entrepreneurship Cell, Cultural Club","Web Development, Python, Data Science, Machine...",...,Startup,5.86,7.72,6.20,5.94,6.99,6.87,7.25,6.43,1781000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,b89a9728-c675-41eb-b950-75ead36ed18b,Amit,23.0,Male,ECE,6.62,4.0,66.61,"Sports Club, Entrepreneurship Cell","Machine Learning, Web Development, Java, SQL, ...",...,Higher Studies,5.43,6.57,6.44,6.77,5.81,6.99,6.67,8.29,1890000.0
1975,4825d876-bf57-4dbe-a8d4-b9cb3b2bb0d0,Siddharth,20.0,Male,EEE,7.55,0.0,66.09,Robotics,"Web Development, Python, SQL",...,Higher Studies,7.59,8.99,7.36,7.77,8.26,7.18,5.45,7.79,1829000.0
1978,2d8ba019-500f-4a92-ad48-f0e37e0710d3,Vikram,22.0,Male,IT,7.92,3.0,62.14,Sports Club,"Java, Python, Machine Learning, Web Developmen...",...,Startup,7.75,7.39,8.18,6.31,8.00,7.16,8.77,9.79,1894000.0
1986,dc9bb95a-8d82-4588-ba3f-476287e09a4b,Amit,19.0,Male,CSE,6.79,1.0,95.93,"Coding Club, Cultural Club","Machine Learning, Web Development",...,Research,6.57,6.46,7.09,7.55,7.12,7.71,5.03,6.78,1710000.0
1990,5e781fd7-94e0-43ba-a9f9-48b24e6384bb,Joseph Coleman,22.0,Male,EEE,7.21,0.0,76.65,"Robotics, Entrepreneurship Cell","Data Science, SQL, Java, Machine Learning",...,Job,6.87,7.99,6.49,5.83,8.21,6.68,7.88,7.76,1118000.0

In [13]:
df[(df['Salary']>1000000)&(df['Gender']=="Female")]

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
10,e87d1c78-e7c4-41c7-8049-7b717d106c60,Anna Henderson,23.0,Female,EEE,7.17,1.0,73.88,Coding Club,"C++, Python, Machine Learning",...,Research,9.54,7.52,6.41,6.87,8.07,6.42,7.85,4.68,1554000.0
12,1750bd26-bcfc-4af5-9881-a1f0fbbb523a,Pooja,23.0,Female,CIVIL,7.50,1.0,99.10,"Coding Club, Robotics, Sports Club","Java, Python, Web Development, Data Science, C++",...,Job,6.68,7.02,6.66,5.36,8.09,7.90,8.99,9.28,1751000.0
14,f0cd7f05-ea87-455e-a382-95d31e0ef546,Lucas Robinson,20.0,Female,ECE,6.22,1.0,92.43,Sports Club,"Data Science, Machine Learning, Java",...,Startup,7.49,4.15,6.14,5.87,6.74,6.46,7.80,5.14,1912000.0
17,7a8d03aa-782a-45e0-88ca-765192f5df7b,Cody Williams,21.0,Female,MECH,7.23,0.0,75.04,"Robotics, Sports Club, Literary Society","Python, Data Science",...,Research,5.99,6.93,7.83,6.97,9.36,7.42,7.23,6.09,1235000.0
19,05a321d4-578e-468a-a1bf-4038a4de8d28,Pooja,22.0,Female,CIVIL,6.71,3.0,86.48,"Literary Society, Entrepreneurship Cell","SQL, Web Development, Java",...,Job,6.40,8.17,5.33,5.51,7.14,7.03,6.28,7.81,1090000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1934,f6d22a7b-aec7-4a82-948b-4376602a4e57,Kimberly Valdez,18.0,Female,EEE,6.92,0.0,79.98,"Robotics, Literary Society","SQL, Data Science, Machine Learning",...,Job,5.77,6.84,7.93,5.50,7.60,6.70,6.03,9.02,1600000.0
1937,e4ad5e9b-fedd-42d9-a26c-bc6a7fe5a4b6,Kelly Le,19.0,Female,EEE,7.09,2.0,99.17,Cultural Club,"Java, Machine Learning, SQL, Data Science, Python",...,Higher Studies,6.83,7.42,6.37,7.23,7.78,6.27,7.78,7.05,1932000.0
1958,a43e558c-2215-4f00-9fdf-0e05c0cef31b,Brenda Moreno MD,19.0,Female,EEE,6.46,0.0,77.92,"Cultural Club, Coding Club","Web Development, Machine Learning, SQL, Data S...",...,Startup,5.55,6.38,8.00,6.45,5.29,6.10,6.71,7.17,1058000.0
1989,0b705933-4cde-4b6b-9132-567c51a40d2a,Ashley Sweeney,20.0,Female,MECH,7.46,0.0,76.28,"Coding Club, Literary Society","Java, Machine Learning",...,Higher Studies,8.25,6.20,8.29,6.75,7.76,7.09,9.23,6.11,1452000.0
1994,e0df9d28-94ae-404e-a5ca-3a2257b0e189,Sonal,23.0,Female,MECH,6.79,1.0,93.35,"Sports Club, Coding Club, Literary Society","SQL, Java, Data Science, Web Development",...,Startup,6.87,6.29,7.27,6.09,7.18,7.49,6.78,6.37,1685000.0

The **info()** method provides a concise summary of a DataFrame, including:

    Index type and range: Information about the DataFrame's index.
    Column names and their data types (dtypes): Identifies whether columns are numeric, object (strings), datetime, etc.
    Non-null counts: Shows the number of non-missing values in each column, which helps in identifying missing data.
    Memory usage: Estimates the memory consumed by the DataFrame.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         1999 non-null   object
 1   Name               2000 non-null   object
 2   Age                1999 non-null   float64
 3   Gender             1999 non-null   object
 4   Branch             1999 non-null   object
 5   Average GPA        1999 non-null   float64
 6   Backlogs           1999 non-null   float64
 7   Attendance (%)     1999 non-null   float64
 8   Clubs              1999 non-null   object
 9   Skills             1999 non-null   object
 10  Internship Done    1999 non-null   object
 11  Internship Domain  982 non-null    object
 12  Placement Status   1999 non-null   object
 13  Placement Domain   1032 non-null   object
 14  CTC (LPA)          1999 non-null   float64
 15  Alumni Path        1032 non-null   object
 16  Sem1 GPA           1999 non-null   float64
 17  Sem2 GPA           1999 non-null   float64
 18  Sem3 GPA           1999 non-null   float64
 19  Sem4 GPA           1999 non-null   float64
 20  Sem5 GPA           1999 non-null   float64
 21  Sem6 GPA           1999 non-null   float64
 22  Sem7 GPA           1999 non-null   float64
 23  Sem8 GPA           1999 non-null   float64
 24  Salary             1999 non-null   float64
dtypes: float64(14), object(11)
memory usage: 390.8+ KB

The describe() method generates descriptive statistics of the DataFrame's columns. By default, it focuses on numerical columns, providing: 

    count: Number of non-null values.
    mean: Average value.
    std: Standard deviation.
    min: Minimum value.
    25% (Q1): 25th percentile (first quartile).
    50% (Q2): 50th percentile (median).
    75% (Q3): 75th percentile (third quartile).
    max: Maximum value.

In [15]:
df.describe()

,Age,Average GPA,Backlogs,Attendance (%),CTC (LPA),Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
count,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.00000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1.999000e+03
mean,20.474237,7.002616,0.966983,78.933147,5.795898,6.976433,7.08021,6.980905,6.961736,7.037894,6.939355,6.990310,7.054812,5.795898e+05
std,1.728062,0.341148,0.990905,11.730931,6.563695,0.966329,1.03160,0.985273,0.983697,0.984407,0.954357,1.018425,1.032945,6.563695e+05
min,18.000000,6.050000,0.000000,60.040000,0.000000,4.000000,4.10000,4.000000,4.000000,4.000000,4.150000,4.000000,4.000000,0.000000e+00
25%,19.000000,6.770000,0.000000,69.000000,0.000000,6.330000,6.39000,6.280000,6.275000,6.370000,6.270000,6.300000,6.355000,0.000000e+00
50%,21.000000,7.000000,1.000000,78.310000,3.460000,6.980000,7.09000,6.940000,6.910000,7.030000,6.930000,6.970000,7.110000,3.460000e+05
75%,22.000000,7.215000,1.000000,89.220000,11.260000,7.670000,7.82000,7.630000,7.640000,7.685000,7.575000,7.700000,7.765000,1.126000e+06
max,23.000000,8.070000,5.000000,99.980000,19.990000,10.000000,10.00000,10.000000,9.630000,9.780000,10.000000,9.920000,10.000000,1.999000e+06

Column selection:

we can find the overall columns

In [16]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain',
       'CTC (LPA)', 'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA',
       'Sem4 GPA', 'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA', 'Salary'],
      dtype='object')

Select multiple columns by using the below syntax

In [17]:
df[['Student ID', 'Branch', 'Average GPA']]

                                Student ID Branch  Average GPA
0     b37412a3-fa5c-40ca-b087-7109a47482d7   MECH         6.99
1     65001423-faeb-4d19-a550-8ea26133a34d    ECE         6.46
2     228aaf1d-8710-4c8d-bfec-001b0df01f34  CIVIL         7.08
3     1aa67474-e200-4157-ad54-c95aaa4d52a8    ECE         6.92
4     5122db4a-14c8-44d7-b2f4-e869f69d3dd7    EEE         7.09
...                                    ...    ...          ...
1995  27d7e5aa-dc11-40a7-9aff-586f00f8d55b     IT         7.69
1996  74f43a77-70a1-4e4c-a0c2-460d939618c9  CIVIL         7.25
1997  88a613b4-a3b8-4f92-a3c9-0c6a86017633    EEE         6.92
1998  248c7b65-0c61-4277-9e95-44857b54d1a9    CSE         7.09
1999  840d718e-de7b-4218-95bd-11db983c3cbd     IT         6.52

[2000 rows x 3 columns]

Filter rows:

In [18]:
df.Age.sort_values(ascending=False)

50      23.0
54      23.0
1981    23.0
1002    23.0
1005    23.0
        ...
90      18.0
96      18.0
102     18.0
446     18.0
863      NaN
Name: Age, Length: 2000, dtype: float64

In [19]:
df[df['Branch'] == 'MECH']

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Salary
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99,0.0
5,28dd6ff3-6391-4421-ba38-3c3164b96252,Siddharth,19.0,Male,MECH,7.36,0.0,62.56,Sports Club,"SQL, Python",...,Startup,5.44,9.08,8.13,8.46,7.03,6.64,6.33,7.81,605000.0
6,5c375254-a8fc-4690-a9b1-c4a1da221b85,Alicia Dillon,18.0,Female,MECH,7.06,2.0,82.62,"Entrepreneurship Cell, Robotics, Cultural Club","Web Development, C++, Machine Learning",...,NaN,7.12,7.23,8.52,7.29,8.39,6.22,5.40,6.35,0.0
17,7a8d03aa-782a-45e0-88ca-765192f5df7b,Cody Williams,21.0,Female,MECH,7.23,0.0,75.04,"Robotics, Sports Club, Literary Society","Python, Data Science",...,Research,5.99,6.93,7.83,6.97,9.36,7.42,7.23,6.09,1235000.0
18,6d59c708-298e-45cc-a9e6-eaa3024e260c,Priya,22.0,Female,MECH,6.49,0.0,71.11,Cultural Club,"Web Development, Python, SQL, C++",...,NaN,8.16,7.12,6.52,7.78,4.62,5.56,6.51,5.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1973,c93c9cc6-668b-48da-8222-cd7f36e6ba85,Joshua Terry,21.0,Male,MECH,6.61,0.0,87.45,"Literary Society, Sports Club","C++, SQL, Machine Learning",...,Job,5.26,6.31,6.82,6.89,5.52,8.15,6.90,7.04,661000.0
1974,3db60d0c-66d4-4e39-8c41-72446d04be48,Rakhi,18.0,Female,MECH,6.74,1.0,75.04,"Cultural Club, Sports Club, Robotics","C++, SQL, Java",...,NaN,7.12,6.03,8.20,6.84,6.97,6.07,6.56,6.12,0.0
1979,b40a3f7d-353d-45f8-b1f0-69a983a0ba0f,Amit,22.0,Male,MECH,6.94,1.0,89.83,"Coding Club, Robotics, Literary Society","C++, Java, Python, Data Science, Web Development",...,NaN,7.08,6.92,7.52,7.27,7.26,5.98,5.31,8.14,0.0
1989,0b705933-4cde-4b6b-9132-567c51a40d2a,Ashley Sweeney,20.0,Female,MECH,7.46,0.0,76.28,"Coding Club, Literary Society","Java, Machine Learning",...,Higher Studies,8.25,6.20,8.29,6.75,7.76,7.09,9.23,6.11,1452000.0
1994,e0df9d28-94ae-404e-a5ca-3a2257b0e189,Sonal,23.0,Female,MECH,6.79,1.0,93.35,"Sports Club, Coding Club, Literary Society","SQL, Java, Data Science, Web Development",...,Startup,6.87,6.29,7.27,6.09,7.18,7.49,6.78,6.37,1685000.0

## 🛠️ 4. Data Cleaning & Preprocessing

Handling nulls: 
Find null values in each colum

In [20]:
df.isnull().sum()

Student ID              1
Name                    0
Age                     1
Gender                  1
Branch                  1
Average GPA             1
Backlogs                1
Attendance (%)          1
Clubs                   1
Skills                  1
Internship Done         1
Internship Domain    1018
Placement Status        1
Placement Domain      968
CTC (LPA)               1
Alumni Path           968
Sem1 GPA                1
Sem2 GPA                1
Sem3 GPA                1
Sem4 GPA                1
Sem5 GPA                1
Sem6 GPA                1
Sem7 GPA                1
Sem8 GPA                1
Salary                  1
dtype: int64

drop null values using **dropna()** of entire dataset

In [21]:
drop_df=df.copy()

In [22]:
drop_df.dropna(inplace=True)

In [23]:
drop_df.shape

(481, 25)

drop null values using dropna() on particular field

In [24]:
drop_df2=df.copy()

In [25]:
drop_df2.dropna(subset=['Placement Domain'], inplace=True)

In [26]:
drop_df2.shape

(1032, 25)

## Type conversions:

In [27]:
df.Age.dtype

dtype('float64')

In [28]:
df_age=df.copy()
df_age['Age']=df_age['Age'].fillna(df_age['Age'].mean())   #before converting int/float we need to remove the nan values

In [29]:
df_age['Age'] = df_age['Age'].astype(int)

In [30]:
df_age.Age.dtype

dtype('int64')

## Renaming columns:

In [31]:
df.rename(columns={'CTC (LPA)': 'Salary'}, inplace=True)

In [32]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain', 'Salary',
       'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA', 'Sem4 GPA',
       'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA', 'Salary'],
      dtype='object')

## 🔄 5. Feature Engineering
## http://localhost:8888/notebooks/Desktop/Medium_Documents/Pandas_Lambda.ipynb

Create new column—e.g. salary category:

In [33]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain', 'Salary',
       'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA', 'Sem4 GPA',
       'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA', 'Salary'],
      dtype='object')

In [34]:
df.Salary.mean()

Salary         5.795898
Salary    579589.794897
dtype: float64

In [35]:
df['Salary_level'] = df['Salary'].apply(lambda x: 'High' if x > df['Salary'].mean() else 'Low')

ValueError: Can only compare identically-labeled Series objects

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         1999 non-null   object
 1   Name               2000 non-null   object
 2   Age                1999 non-null   float64
 3   Gender             1999 non-null   object
 4   Branch             1999 non-null   object
 5   Average GPA        1999 non-null   float64
 6   Backlogs           1999 non-null   float64
 7   Attendance (%)     1999 non-null   float64
 8   Clubs              1999 non-null   object
 9   Skills             1999 non-null   object
 10  Internship Done    1999 non-null   object
 11  Internship Domain  982 non-null    object
 12  Placement Status   1999 non-null   object
 13  Placement Domain   1032 non-null   object
 14  Salary             1999 non-null   float64
 15  Alumni Path        1032 non-null   object
 16  Sem1 GPA           1999 non-null   float64
 17  Sem2 GPA           1999 non-null   float64
 18  Sem3 GPA           1999 non-null   float64
 19  Sem4 GPA           1999 non-null   float64
 20  Sem5 GPA           1999 non-null   float64
 21  Sem6 GPA           1999 non-null   float64
 22  Sem7 GPA           1999 non-null   float64
 23  Sem8 GPA           1999 non-null   float64
 24  Salary             1999 non-null   float64
dtypes: float64(14), object(11)
memory usage: 390.8+ KB

In [ ]:
df.Salary_level.value_counts()

## 🧮 6. GroupBy & Aggregation  http://localhost:8888/notebooks/Desktop/Medium_Documents/Pandas_Groupby.ipynb

Mean CGPA per branch:

In [38]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain', 'Salary',
       'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA', 'Sem4 GPA',
       'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA', 'Salary'],
      dtype='object')

In [39]:
df.groupby('Branch')['Sem1 GPA'].mean().sort_values(ascending=False)

Branch
CIVIL    7.052557
IT       7.016462
MECH     7.006034
ECE      6.994458
EEE      6.947864
CSE      6.815034
Name: Sem1 GPA, dtype: float64

In [41]:
df.columns

Index(['Student ID', 'Name', 'Age', 'Gender', 'Branch', 'Average GPA',
       'Backlogs', 'Attendance (%)', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain', 'Salary',
       'Alumni Path', 'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA', 'Sem4 GPA',
       'Sem5 GPA', 'Sem6 GPA', 'Sem7 GPA', 'Sem8 GPA', 'Salary'],
      dtype='object')

Custom aggregation:

In [42]:
df.groupby('Gender').agg({'Sem1 GPA': ['mean', 'max'], 'Salary': 'median'})

AttributeError: 'DataFrame' object has no attribute 'name'

## 🧠 7. Pivot Table & Crosstab
## http://localhost:8888/notebooks/Desktop/Medium_Documents/Pandas_Pivot_table.ipynb
Pivot example:

In [ ]:
pd.pivot_table(df, index='Branch', columns='Salary_level', values='Sem1 GPA', aggfunc='mean')

Crosstab example:

In [ ]:
pd.crosstab(df['Placement Status'], df['Salary_level'])

## 🔁 8. Handling Time/Ordering (if present)  

## http://localhost:8888/notebooks/Desktop/Medium_Documents/Pandas_Time_Series.ipynb
    If dataset has dates, show datetime conversion:

In [ ]:
df['placed_date']=pd.date_range(start='2023-01-01', periods=len(df), freq='W')  #create dummy date

In [ ]:
df['Placement Status'].value_counts()

In [ ]:
filt_df=df[df['Placement Status']=="Not Placed"]
filt_df['placed_date']=pd.NaT

In [ ]:
df=df[df['Placement Status']=="Placed"]
df=pd.concat([df,filt_df],ignore_index=False)

In [ ]:
df['Placement Status'].value_counts()

In [ ]:
df.placed_date.value_counts()

In [ ]:
df

In [ ]:
df['placed_date'] = pd.to_datetime(df['placed_date'])
df.set_index('placed_date', inplace=True)
df.resample('M')['Salary'].mean()

## 🎯 9. Mini Analysis
    Top 5 branches by mean salary

    Relationship between CGPA and salary (scatter + correlation)

    Salary comparison by gender or other features

In [ ]:
df.columns

In [ ]:
df.groupby('Branch')['Salary'].mean().sort_values(ascending=False).head()

## Relationship Between CGPA and Salary

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.scatterplot(data=df, x='Sem1 GPA', y='Salary')
plt.title('CGPA vs Salary')
plt.xlabel('CGPA')
plt.ylabel('Salary')
plt.show()

In [ ]:
# Correlation
correlation = df[['Sem1 GPA', 'Salary']].corr()
correlation

## Salary Comparison by Gender

In [ ]:
sns.boxplot(data=df, x='Gender', y='Salary')
plt.title('Salary Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Salary')
plt.show()